### ISSUE TITLE
Addon bugged in 4.1.1 ?

### ISSUE THREAD

**Issue by JDLRx** [HolonProduction/godot_kanban_tasks#18] opened 2023-08-30 09:32 UTC
I was trying to install the addon but after restarting the engine there was no button at the top to access the addon and also it lead to
the other 4 buttons including the assetLib to be bugged thinking my window size streches over all my 3 screens when it was not.

See my post here for clarification: https://godotforums.org/d/35880-assetslib-bug

**Comment by HolonProduction** [comment] 2023-08-30 09:48
I can't reproduce the issue on my PC. So some more Info might be helpfull to figure the bug out.
- Which OS are you using?
- How are you restarting the editor (quit to project manager or completly closing everything)?
- How did you get Godot engine (Steam, from the Website,...)
- Also sharing you project files may help to figure out what went wrong (offcourse only if you want to share them).
- Does the problem occure in other projects, that you didn't install the plugin in? (If no: can you consistently reproduce the problem in a freshly created project?)

Aside from that: Did you try to disable the plugin in the project settings?

**Comment by JDLRx** [comment] 2023-08-30 10:24
I reinstalled the addon, now the addon works atleast but the asset lib stretch is still ongoing

OS is Windows 10

Did a full engine restart

Godot 4.1.1 exe from website

The AssetsLib stretch happens in all my projects now so I don't think it has to do with the assets

yes also happens to new projects

Also maybe this helps to see the problem better
https://www.youtube.com/watch?v=N_gfMTnjcaI

some of the sort function in assetslib are working as intended

**Comment by JDLRx** [comment] 2023-08-30 19:14
@HolonProduction you can close this issue, there is a bug with the AssetsLib in godot
which produces this bug when the addon names are very long
https://github.com/godotengine/godot/issues/80507

but nothing wrong with this addon, im using it for the whole day and loving it ty! :)

**Comment by HolonProduction** [comment] 2023-09-01 11:10
Great that you love it. Feel free to come back if you encounter a bug with the plugin.

**Closed by HolonProduction** 2023-09-01 11:10 UTC
Labels: bug
