### ISSUE TITLE
Exported version crashes upon save

### ISSUE THREAD

**Issue by MarioLiebisch** [HolonProduction/godot_kanban_tasks#11] opened 2022-11-19 22:44 UTC
Maybe I'm doing something wrong, maybe it's actually a bug in Godot's current version (x64 release build for Windows).

I've setup an export definition to create a standalone version of the editor and it works fine, but it crashes as soon as the editor tries to save changes to `data.json`. I suspect this happens due to it being a `res://` URL. I changed it to just `./data.json` (which is where I wanted to save it), and this seems to actually be working.

**Comment by HolonProduction** [comment] 2022-11-20 11:01
The porting as standalone app is not completely done. There are still things that need to be changed (for example the save location). I am currently seperating the data from the visuals of the plugin. When this is done I willl rework the saving and loading.

**Comment by HolonProduction** [comment] 2023-03-01 15:24
Took some time but should be fixed by 86a86b1bec05ab276b9071b3dafc1f03b250368e.

**Closed by HolonProduction** 2023-03-01 15:24 UTC
Labels: bug

**Comment by Penime** [comment] 2024-01-09 11:53
thank you for the kanban task plugin I think it's very useful plugin
I want to report bug, actually I think this is the same bug Mario Liebisch experience.
I downloaded the export version for windows, from [itch](https://holonproduction.itch.io/kanban-tasks) and when I tried to save after deleting a task from the board, ither as .kanban or .json the program crashed with error `ERROR: Condition "!data.tree" is true. Returning: nullptr`.

Steps to reproduce the bug:
  1. run kanban_task.exe
  2. create a board with 1 or more task
  3. save the board
  4. delete a task
  5. save the board

Screenshot:
![image](https://github.com/HolonProduction/godot_kanban_tasks/assets/122761839/0fe49650-9725-4830-a437-81131250fbb9)

Environments:
Environment 1
1. windows 10 pro
2. OpenGL API 3.3.0 - Build 20.19.15.5166 - Compatibility - Using Device: Intel - Intel(R) HD Graphics 4600
3. Kanban_task Versions [standalone, 2.0_Beta_3]

Environment 2
1. windows 10
2. Vulkan API 1.2.170 - Forward+ - Using Vulkan Device #0: AMD - AMD Radeon 610 Series
3. Kanban_task Versions [standalone, 2.0_Beta_3]

**Comment by Penime** [comment] 2024-01-10 12:54
I tried to solve it myself, so I downloaded the project from github and opened the project in Godot, but I don't understand the code. (I'm still at the beginning of learning Godot).
Anyway as you can see in the recording, if I force Godot to continue it manages to save the .kanban file successfully.

https://github.com/HolonProduction/godot_kanban_tasks/assets/122761839/6d944a85-910d-43d4-990c-f21853e90784

**Comment by HolonProduction** [comment] 2024-01-10 14:14
Fixed in 5ea0ade. (Was a different issue. So if you report something else in the future please open a new issue and don't comment on closed ones. It's easier to keep track of everything this way :) )

Also what is going on with the pen icon in your video?

**Comment by Penime** [comment] 2024-01-10 14:58
Thank you
(Sorry I'm new to github, I won't comment on a closed topic anymore.)
I actually don't know what happened to the icon, I just downloaded the project file by file and created the related folder, because I wanted the project.godot file and all the files that not provided in the github releases.
And the icon appear big when I opened it in godot.
